services:
  mariadb:
    container_name: mariadb
    secrets:
      - db_password
      - db_root_password
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - data_dir:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    container_name: wordpress
    secrets:
      - db_password
      - db_root_password
    build: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress_net
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress_net
    depends_on:
      - wordpress
    restart: always

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    ports:
      - "8080:8080"
    networks:
      - wordpress_net
    depends_on:
      - nginx
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:wr
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - wordpress_net
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

volumes:
  data_dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/merboyac/data/mysql
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/merboyac/data/wordpress

networks:
  wordpress_net:
    driver: bridge